name: Build and test Go

on:
  pull_request:


jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.20.3
    
    - name: Install depedencies
      run: |
        go mod download
        go mod tidy -v

    - name: Build project
      run: |
        make build
    
    - name: Test project
      run: |
        make test
  
  Publish:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.20.3
    
    - name: Install depedencies
      run: |
        go mod download
        go mod tidy -v
    
    - name: Publish to production
      run: |
        make production/deploy